import { WorkspaceShell } from "@/components/workspace/WorkspaceShell";
import { ArrowRight, BrainCircuit, Braces, CalendarDays, Cloud, Database, Globe2, Layers3, Mail, Route, ShieldCheck, TimerReset, type LucideIcon } from "lucide-react";

const TONE = { orange: "bg-[#fff0e7] text-[#c7501b]", violet: "bg-[#f2edff] text-[#6d48a2]", blue: "bg-[#eaf2ff] text-[#2563eb]", green: "bg-[#eaf6ef] text-[#27724d]" };
function Card({ Icon, label, title, text, tone }: { Icon: LucideIcon; label: string; title: string; text: string; tone: keyof typeof TONE }) {
  return <article className="min-h-[172px] rounded-[22px] border border-[#eaded6] bg-white p-5 shadow-[0_10px_28px_rgba(74,40,22,0.06)]"><div className={"grid h-11 w-11 place-items-center rounded-xl " + TONE[tone]}><Icon className="h-5 w-5" /></div><p className="mt-4 text-[11px] font-bold tracking-[0.12em] text-[#99786a]">{label}</p><h2 className="mt-1 text-lg font-bold text-[#332118]">{title}</h2><p className="mt-2 text-sm leading-6 text-[#80695e]">{text}</p></article>;
}

export default function StackPage() {
  return <WorkspaceShell><div className="mx-auto max-w-[1500px] px-5 py-6 sm:px-7 sm:py-8">
    <header className="rounded-[26px] border border-[#f0ded3] bg-[#fffaf6] px-6 py-7 shadow-[0_12px_40px_rgba(93,49,23,0.06)] sm:px-8"><p className="text-xs font-bold tracking-[0.14em] text-[#c7501b]">DAILYNEWS STACK</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[#332118] sm:text-4xl">情報を見つけて、あなた向けに育てる仕組み</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#80695e]">公開情報・X API・Google連携を、このPC内のDailyNewsが収集・整理します。個人の判定はローカルSQLiteに保存され、次の表示順へ反映されます。</p></header>
    <section className="mt-5 rounded-[26px] border-2 border-dashed border-[#e5cfc1] bg-[#fffefd] p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold tracking-[0.12em] text-[#c7501b]">MAIN FLOW</p><h2 className="mt-1 text-xl font-bold text-[#332118]">DailyNewsの中核</h2></div><span className="rounded-full bg-[#fff0e7] px-3 py-1.5 text-xs font-bold text-[#a84921]">このPCで動作・保存</span></div><div className="mt-6 grid items-stretch gap-3 xl:grid-cols-[1fr_auto_1fr_auto_1fr]"><Card Icon={Layers3} label="FRONTEND" title="Next.js / React" text="ホーム、Xフィード、技術イベント、インターン募集をカードで表示。" tone="orange" /><div className="hidden items-center justify-center text-[#c7764a] xl:flex"><ArrowRight className="h-7 w-7" /></div><Card Icon={Route} label="API & LOGIC" title="Route Handlers" text="収集、判定の保存、Google OAuth、表示用データの組み立て。" tone="violet" /><div className="hidden items-center justify-center text-[#c7764a] xl:flex"><ArrowRight className="h-7 w-7" /></div><Card Icon={Database} label="LOCAL DATA" title="Prisma + SQLite" text="候補、判定理由、興味語、収集履歴を prisma/dev.db に保存。" tone="blue" /></div></section>
    <section className="mt-5 grid gap-4 lg:grid-cols-[1.05fr_1fr]"><div className="rounded-[24px] border border-[#eaded6] bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#fff0e7] text-[#c7501b]"><Globe2 className="h-5 w-5" /></div><div><p className="text-xs font-bold tracking-[0.12em] text-[#a87963]">INPUTS</p><h2 className="font-bold text-[#332118]">どこから情報が来る？</h2></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Card Icon={Cloud} label="X API" title="公式アカウントの告知" text="インターン、技術イベント、ITニュースを上限付きで取得。" tone="blue" /><Card Icon={Braces} label="PUBLIC WEB" title="企業・イベント公式ページ" text="robots.txtと公開条件を確認して、採用・イベント情報を収集。" tone="orange" /><Card Icon={Mail} label="GOOGLE GMAIL" title="関連メールだけ" text="技術イベント・インターンに関係するメールを抽出して表示。" tone="green" /><Card Icon={CalendarDays} label="GOOGLE CALENDAR" title="予定との照合" text="Googleログインで許可したカレンダー予定を読み取り。" tone="violet" /></div></div><div className="rounded-[24px] border border-[#eaded6] bg-[#fffaf6] p-5 sm:p-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#f2edff] text-[#6d48a2]"><BrainCircuit className="h-5 w-5" /></div><div><p className="text-xs font-bold tracking-[0.12em] text-[#8a6ca2]">PERSONALIZATION</p><h2 className="font-bold text-[#332118]">どうやってあなた向けになる？</h2></div></div><ol className="mt-5 space-y-3 text-sm leading-6 text-[#80695e]"><li><b className="text-[#43281a]">1. 候補をスコア化</b><br />技術分野、イベント形式、公式情報かどうかを評価します。</li><li><b className="text-[#43281a]">2. 興味あり・なしを学習</b><br />判定と「合わなかった理由」の語句を加点・減点に利用します。</li><li><b className="text-[#43281a]">3. 次の並び順へ反映</b><br />興味に合う候補を優先し、避けたい話題は下げます。</li></ol><div className="mt-5 rounded-xl border border-[#eaded6] bg-white px-4 py-3 text-xs leading-5 text-[#80695e]"><ShieldCheck className="mr-1 inline h-4 w-4 text-[#27724d]" />個人の判定データは外部に送信せず、このPCのSQLiteに保存します。</div></div></section>
    <section className="mt-5 rounded-[24px] border border-[#eaded6] bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#eaf6ef] text-[#27724d]"><TimerReset className="h-5 w-5" /></div><div><p className="text-xs font-bold tracking-[0.12em] text-[#4a8a67]">AUTOMATION</p><h2 className="font-bold text-[#332118]">毎日の更新</h2></div></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-[#faf8f6] p-4"><p className="text-xs text-[#92796d]">5:00</p><p className="mt-1 font-bold text-[#43281a]">Windows タスク</p><p className="mt-1 text-xs leading-5 text-[#80695e]">収集スクリプトを起動します。</p></div><div className="rounded-xl bg-[#faf8f6] p-4"><p className="text-xs text-[#92796d]">収集後</p><p className="mt-1 font-bold text-[#43281a]">候補を保存・更新</p><p className="mt-1 text-xs leading-5 text-[#80695e]">取得日時・収集元も一緒に記録します。</p></div><div className="rounded-xl bg-[#faf8f6] p-4"><p className="text-xs text-[#92796d]">表示時</p><p className="mt-1 font-bold text-[#43281a]">あなた向けに並べ替え</p><p className="mt-1 text-xs leading-5 text-[#80695e]">判定履歴と興味語を使って順位を計算します。</p></div></div></section>
  </div></WorkspaceShell>;
}
